spring:
  redis:
    host: 119.29.185.91
    password: lu19991024
    port: 5269
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: lu19991024
    username: lyx
    url: jdbc:mysql://119.29.185.91:12322/cat_life?charset=utf8&useSSL=false
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis

server:
  port: 8657

wx:
  info:
    url: https://api.weixin.qq.com/sns/jscode2session
    appId:
    secret:
    grantType: authorization_code
